name: Flutter Web Build Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter build web --release
